version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_nbs
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/nbsdb
      SPRING_DATASOURCE_USERNAME: nbsuser
      SPRING_DATASOURCE_PASSWORD: nbspassword
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: nbs_db
    environment:
      POSTGRES_USER: nbsuser
      POSTGRES_PASSWORD: nbspassword
      POSTGRES_DB: nbsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

