spring.application.name=nbsback
# Application version
application.version=0.0.1-SNAPSHOT

# Configuración de base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5454/nbs_database
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# Specify Hibernate dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Strava API Configuration
strava.client.id=197588
strava.client.secret=aecc6c347c6aefed40bd95c92048e4d5af2c48ac
strava.redirect.uri=http://localhost:8080/auth/strava/exchange

strava.callback.url=http://nbsb.pdrgmz.uk/webhook
strava.verify.token=STRAVA_VERIFY_TOKEN_NBSB

# Base URL for Strava API
strava.api.base-url=https://www.strava.com/api/v3







